thoth-station/investigator

- Pipfile
- Pipfile.lock
> Add Pipfile and Pipfile.lock

- thoth/unresolved_package_handler/unresolved_package_handler.py
Remove parameters not required to schedule solver.
> Remove not required parameters

- Pipfile.lock
- README.md
- consumer.py
- producer.py
- thoth/investigator/__init__.py
- thoth/investigator/investigate_unresolved_package.py
Modify files due to update in name of the component.
> Modify code and update README after renaming the component

- consumer.py
> minor missing piece

- thoth/investigator/investigate_unresolved_package.py
Fixes: https://github.com/thoth-station/investigator/issues/70
`It requires new release of thoth-investigator`
Correct parameter requested by consumer.
> Correct parameter from Kafka message

- producer.py
By using gather instead of `await` we increase the degree of multiprogramming, making time spent waiting for `IO` much smaller.
> Make producer more asynchronous by creating all futures before awaiting

- consumer.py
- thoth/investigator/investigate_unresolved_package.py
Create Prometheus metrics server for consumer.
See: https://github.com/thoth-station/investigator/issues/25
> Add a few persistent metrics

- app.sh
Signed-off-by: Christoph Görn <goern@redhat.com>
put in some default for parameters, set the web host of Faust to 0.0.0.0
> a little more roubust app.sh

- thoth/investigator/investigate_unresolved_package.py
Fixes: https://github.com/thoth-station/investigator/issues/89
Fix issue and move logic
> Add Missing connection to database

- thoth/investigator/investigate_unresolved_package.py
```
[2020-07-17 14:18:15,730] [1] [WARNING] Failed to schedule solver for package black===* from ['https://tensorflow.pypi.thoth-station.ninja/index/rhel7.7/AVX2/simple', 'https://tensorflow.pypi.thoth-station.ninja/index/rhel7.6/AVX2/simple', 'https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple', 'https://pypi.python.org/simple', 'https://tensorflow.pypi.thoth-station.ninja/index/rhel7.5/AVX2/simple', 'https://pypi.org/simple'] 
```
Add more logs to debug
> Add more logging

- thoth/investigator/investigate_unresolved_package.py
Fixes: https://github.com/thoth-station/investigator/issues/101
Fixes: https://github.com/thoth-station/solver/issues/584
Add logic to schedule solvers, revsolver, security indicators when UnresolvedPackageMessage is received
> Schedule workflows

- Pipfile
- Pipfile.lock
- consumer.py
- producer.py
Adjust initialization of Faust app with new implementation of thoth-messaging
> Adjust app initialization with new implementation in thoth-messaging

- producer.py
- thoth/investigator/investigate_unresolved_package.py
Consider case where all versions are requested ("*").
> Consider all versions explicitly and loop backward from latest

- README.md
- consumer.py
- thoth/investigator/common.py
- thoth/investigator/investigate_unresolved_package.py
- thoth/investigator/investigate_unrevsolved_package.py
Handle Unrevsolved Package Message
> Add methods to handle Unrevsolved Package Message

- Pipfile.lock
- producer.py
Closes https://github.com/thoth-station/messaging/issues/230
> add component and version to message

- consumer.py
- investigator/investigator/adviser_re_run/__init__.py
- investigator/investigator/adviser_re_run/investigate_adviser_re_run.py
- investigator/investigator/adviser_re_run/metrics_adviser_re_run.py
- investigator/investigator/metrics.py
- investigator/investigator/solved_package/investigate_solved_package.py
- investigator/investigator/unresolved_package/investigate_unresolved_package.py
- investigator/investigator/unrevsolved_package/investigate_unrevsolved_package.py
Related-To: https://github.com/thoth-station/investigator/issues/63
Add parse AdviserReRun message to investigator
> Add Investigate AdviserReRunMessage to Investigator

- README.md
- consumer.py
- investigator/investigator/si_unanalyzed_package/__init__.py
- investigator/investigator/si_unanalyzed_package/investigate_si_unanalyzed_package.py
- investigator/investigator/si_unanalyzed_package/metrics_si_unanalyzed_package.py
Closes #204 
Fixes: https://github.com/thoth-station/graph-refresh-job/issues/430
Depends on - #210
> Added logic to process SI Unanalyzed messages

- Pipfile
- Pipfile.lock
- consumer.py
- investigator/investigator/adviser_trigger/__init__.py
- investigator/investigator/adviser_trigger/investigate_adviser_trigger.py
- investigator/investigator/adviser_trigger/metrics_adviser_trigger.py
- investigator/investigator/kebechet_trigger/__init__.py
- investigator/investigator/kebechet_trigger/investigate_kebechet_trigger.py
- investigator/investigator/kebechet_trigger/metrics_kebechet_trigger.py
- investigator/investigator/package_extract_trigger/__init__.py
- investigator/investigator/package_extract_trigger/investigate_package_extract_trigger.py
- investigator/investigator/package_extract_trigger/metrics_package_extract_trigger.py
- investigator/investigator/provenance_checker_trigger/__init__.py
- investigator/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
- investigator/investigator/provenance_checker_trigger/metrics_provenance_checker_trigger.py
- investigator/investigator/qebhwt_trigger/__init__.py
- investigator/investigator/qebhwt_trigger/investigate_qebhwt_trigger.py
- investigator/investigator/qebhwt_trigger/metrics_qebhwt_trigger.py
https://github.com/thoth-station/user-api/pull/1063
Consumers for messages produced in the above PR
Fixes: https://github.com/thoth-station/investigator/issues/205
> add consumers for workflow triggers

- investigator/investigator/kebechet_trigger/investigate_kebechet_trigger.py
- investigator/investigator/package_extract_trigger/investigate_package_extract_trigger.py
patch fix the variable reference for metrics
> patch fix the variable reference for metrics

- README.md
- investigator/investigator/advise_justification/README.md
- investigator/investigator/adviser_re_run/README.md
- investigator/investigator/adviser_trigger/README.md
- investigator/investigator/hash_mismatch/README.md
- investigator/investigator/kebechet_trigger/README.md
- investigator/investigator/missing_package/README.md
- investigator/investigator/missing_version/README.md
- investigator/investigator/package_extract_trigger/README.md
- investigator/investigator/package_released/README.md
- investigator/investigator/provenance_checker_trigger/README.md
- investigator/investigator/qebhwt_trigger/README.md
- investigator/investigator/si_unanalyzed_package/README.md
- investigator/investigator/solved_package/README.md
- investigator/investigator/unresolved_package/README.md
- investigator/investigator/unresolved_package/investigate_unresolved_package.py
- investigator/investigator/unrevsolved_package/README.md
> Update and refactor docs

- README.md
- investigator/investigator/common.py
```
2020-09-18 14:54:06,111   1 WARNING  mode.redirect:838: --- Logging error ---
2020-09-18 14:54:06,114   1 WARNING  mode.redirect:838: Traceback (most recent call last):
2020-09-18 14:54:06,114   1 WARNING  mode.redirect:838: File "/usr/lib64/python3.6/logging/__init__.py", line 994, in emit
msg = self.format(record)
2020-09-18 14:54:06,114   1 WARNING  mode.redirect:838: File "/opt/app-root/lib/python3.6/site-packages/daiquiri/handlers.py", line 111, in format
s = super(TTYDetectorStreamHandler, self).format(record)
2020-09-18 14:54:06,114   1 WARNING  mode.redirect:838: File "/usr/lib64/python3.6/logging/__init__.py", line 840, in format
return fmt.format(record)
2020-09-18 14:54:06,114   1 WARNING  mode.redirect:838: File …
```
> Adjust logging

- README.md
- investigator/investigator/adviser_trigger/README.md
> Adjust links in README

- investigator/investigator/unresolved_package/__init__.py
- producer.py
Related-to: https://github.com/thoth-station/workflow-helpers/pull/110
correct the investigate_unresolved_package import
> correct the investigate_unresolved_package import

- investigator/investigator/missing_version/investigate_missing_version.py
> make func async

- README.md
> add all env variables to README

- investigator/investigator/update_provide_source_distro/investigate_update_provide_source_distro.py
> Add missing metrics

- investigator/investigator/common.py
- investigator/investigator/hash_mismatch/investigate_hash_mismatch.py
- investigator/investigator/missing_package/investigate_missing_package.py
- investigator/investigator/missing_version/investigate_missing_version.py
> Add metrics to see what workflows are scheduled

- README.rst
> Correct link

- .thoth.yaml
> add KPostOffice to list of maintainers

- .aicoe-ci.yaml
- Pipfile.lock
adjust aicoe-ci and update the packages
Related-to: #383
> adjust aicoe-ci and update the packages

- thoth/investigator/common.py
> Remove use-before-declared linter warning

- thoth/investigator/common.py
> Do not use mutable arguments in functions

- Pipfile.lock
Given the PyPI is partially down and responds 502, let's trigger manual update of dependencies for now. Kebechet reports issues while updating.
> Manual update of dependencies

- consumer.py
- thoth/investigator/build_analsysis_trigger/README.md
- thoth/investigator/build_analsysis_trigger/__init__.py
- thoth/investigator/build_analsysis_trigger/investigate_build_analysis_trigger.py
- thoth/investigator/build_analsysis_trigger/metrics_build_analysis_trigger.py
Depends-On: https://github.com/thoth-station/messaging/pull/326
Depends-On: https://github.com/thoth-station/user-api/pull/1171
Depends-On: https://github.com/thoth-station/common/pull/1073
Depends-On: https://github.com/thoth-station/common/pull/1076
> Buildlog analysis trigger

- Pipfile.lock
Not sure why kebechet did not provide update/
> Update dependencies to have more recent thoth-common

- .github/ISSUE_TEMPLATE/kebechet_info.md
- .github/ISSUE_TEMPLATE/kebechet_update.md
> Add "Kebechet update" and "Kebechet info" issue templates

- consumer.py
- thoth/investigator/metrics.py
Related-To: https://github.com/thoth-station/metrics-exporter/issues/529
> Add metric schema

- Pipfile
- Pipfile.lock
Direct dependency had to be adjusted, otherwise Pipenv was unable to lock the stack.
> Manual dependency update

- thoth/investigator/adviser_re_run/investigate_adviser_re_run.py
- thoth/investigator/adviser_trigger/investigate_adviser_trigger.py
- thoth/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
Fixes: #902
Depends-On: thoth-station/common#1109
Related: thoth-station/adviser#1670
Related: thoth-station/management-api#705
> Do not pass arguments that are prepared in adviser container

- .aicoe-ci.yaml
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/major-release.md
- .github/ISSUE_TEMPLATE/minor-release.md
- .github/ISSUE_TEMPLATE/patch-release.md
- .prow.yaml
- OWNERS
Signed-off-by: Christoph Görn <goern@redhat.com>
standard update of CI config, OWNERS
> :arrow_up: update pre-commit plugins, CI related configs

- thoth/investigator/kebechet_run_url_trigger/investigate_kebechet_run_url_trigger.py
- thoth/investigator/package_extract_trigger/investigate_package_extract_trigger.py
> add new args to function call

- Pipfile
- Pipfile.lock
relock the dependencies
Fixes: #464 
Related-to: https://github.com/thoth-station/common/pull/1126
> relock the dependencies

- thoth/investigator/adviser_trigger/investigate_adviser_trigger.py
- thoth/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
related: https://github.com/thoth-station/messaging/pull/375
> add new function args to call

- README.rst
- setup.py
> Changes for publishing on thoth-station.ninja

- Pipfile
- Pipfile.lock
> Constrain thoth-messaging to <=0.13

- thoth/investigator/adviser_trigger/investigate_adviser_trigger.py
- thoth/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
Related: https://github.com/thoth-station/messaging/pull/390/
> Adviser trigger message v4

- thoth/investigator/adviser_trigger/investigate_adviser_trigger.py
- thoth/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
> Fix type for the authenticated parameter

- Pipfile.lock
Relock the dependencies for fix sqlalchemy-utils
Fixes: #507
> Relock the dependencies for fix sqlalchemy-utils

- consumer.py
https://github.com/thoth-station/investigator/issues/511
> messages are no longer classes

- Pipfile
- Pipfile.lock
thoth-sourcemanagement not used
> remove thoth-sourcemanagement from dependencies

- thoth/investigator/unresolved_package/investigate_unresolved_package.py
thoth-station/graph-refresh-job#598
Make investigator expect single index
> expect only single index in message contents

- thoth/investigator/unresolved_package/investigate_unresolved_package.py
https://github.com/thoth-station/messaging/pull/430
> remove inner loop which loops over registered indexes

- thoth/investigator/missing_package/investigate_missing_package.py
> mark missing packages and schedule keb admin

- README.rst
> add docs for  envvar and  endpoint

- README.rst
- consumer.py
- thoth/investigator/metrics.py
> rename from 'paused' to 'halted'

- .pre-commit-config.yaml
- .prow.yaml
- setup.py
- thoth/investigator/cve_provided/investigate_cve_provided.py
- thoth/investigator/hash_mismatch/investigate_hash_mismatch.py
- thoth/investigator/kebechet_trigger/investigate_kebechet_trigger.py
- thoth/investigator/metrics.py
- thoth/investigator/missing_package/investigate_missing_package.py
- thoth/investigator/missing_version/investigate_missing_version.py
- thoth/investigator/package_released/investigate_package_released.py
- thoth/investigator/solved_package/investigate_solved_package.py
> Adjust CI prow

- README.rst
- consumer.py
- thoth/investigator/configuration.py
closes: #554
Ack on fail can now be configured by both using a boolean and also a json serializable list of strings
> add option to pass list as ack on fail envvar

- thoth/investigator/adviser_trigger/investigate_adviser_trigger.py
Fixes: https://github.com/thoth-station/investigator/issues/578
> Enable v5 of adviser trigger messaging

- pyproject.toml
- thoth/investigator/common.py
> Update pyproject.toml to use Python 3.8

- .pre-commit-config.yaml
- Pipfile
- Pipfile.lock
Fix package update issue for kebechet
Fixes: #634
> Fix package update issue for kebechet
